// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActivitiesUpdateController from "./activities_update_controller"
application.register("activities-update", ActivitiesUpdateController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)
